### ISSUE TITLE
ReadAt/WriteAt for File on windows

### ISSUE THREAD

**Issue by MaulingMonkey** [vi/read_write_at#1]
Saw this referenced in https://github.com/sbillig/buffered_offset_reader/issues/2.  Nice crate!  I see ReadAt/WriteAt are intentionally not implemented for File on windows as seek_read/seek_write affect seek state.  While this makes sense, those also take `&self`, and it'd be nice to have some kind of opt-in means of getting ReadAt/WriteAt without resorting to (another) Mutex.  Thought I'd mull over some options before flinging random pull requests your way:

### 1. Simply impl ReadAt/WriteAt for File

Could be hidden behind an opt-in feature?

### 2. Create an opaque type that can be wrapped around File.

Perhaps it'd save the original seek position and restore it if unwrapped back to the inner value?

```rust
use std::fs::File;
use std::io::{self, Seek, SeekFrom};

struct SeeklessFile {
    original: u64,
    file: File
}

impl SeeklessFile {
    pub fn new(mut file: File) -> io::Result<Self> {
        Ok(Self{
            original: file.seek(SeekFrom::Current(0))?,
            file,
        })
    }
    pub fn into_inner(mut self) -> io::Result<File> {
        self.file.seek(SeekFrom::Start(self.original))?;
        Ok(self.file)
    }
}

impl ReadAt  for SeeklessFile { ... }
impl WriteAt for SeeklessFile { ... }
```

These could still cause spooky action at a distance by modifying the seek state of other Files created through [File::try_clone](https://doc.rust-lang.org/std/fs/struct.File.html#method.try_clone), but that can happen without read_write_at and these extension methods anyways.

It might be nice to have some kind of `IntoReadAt` / `IntoWriteAt` traits to accompany this type:
```rust
trait IntoReadAt {
    type ReadAt : ReadAt;
    fn into_read_at(self) -> io::Result<Self::ReadAt>;
}

#[cfg(windows)]
impl IntoReadAt for File {
    type ReadAt = SeeklessFile;
    ...
}

impl<RA: ReadAt> IntoReadAt for RA {
    type ReadAt = RA;
    ...
}
```

I believe stable rustc won't let me implement similar traits in a downstream crate currently, as read_write_at has the option of extending ReadAt to include File which would make the two impls ambiguous... unless implemented in read_write_at.

### 3. ???

I'm sure there's more options I'm not thinking of.

### Why?

I want to get rid of the Mutex spam in https://github.com/MaulingMonkey/vfs-zip .  I'm planning on changing:

[ZipReadOnly::new_*](https://github.com/MaulingMonkey/vfs-zip/blob/532c1582b4993dd69f0d0ad690b95dfae4bbbaba/src/read/_read.rs#L26-L33):
```rust
impl<IO: Read + Seek + Send> ZipReadOnly<IO> {
    pub fn new_strict(io: IO) -> Result<Self> { Self::new_impl(io, false) }
    pub fn new_relaxed(io: IO) -> Result<Self> { Self::new_impl(io, true) }
    ...
```

To take `ReadAt`s:
```rust
impl<R: ReadAt + Sync> ZipReadOnly<R> {
    pub fn new_strict(io: R) -> Result<Self> { Self::new_impl(io, false) }
    pub fn new_relaxed(io: R) -> Result<Self> { Self::new_impl(io, true) }
    ...
```
```rust
impl<R: ReadAt + Sync> ZipReadOnly<R> {
    pub fn new_strict(io: impl IntoReadAt<ReadAt = R>) -> Result<Self> { Self::new_impl(io.into_read_at(), false) }
    pub fn new_relaxed(io: impl IntoReadAt<ReadAt = R>) -> Result<Self> { Self::new_impl(io.into_read_at(), true) }
    ...
```

**Comment by vi** [comment]
If `IO: Read + Seek + Send`  is OK then maybe `IO: ReadAtMut` would also be OK?

**Comment by vi** [comment]
Note that hard coded `io::Result` in trait methods is going to be refactored into an associated type for `Error` in version 0.2.

Would it cause inconvenience for you?

**Comment by MaulingMonkey** [comment]
> If `IO: Read + Seek + Send` is OK then \[...\]

It's kinda not.  Right now I [wrap "everything" in a Mutex](https://docs.rs/vfs-zip/0.2.1/src/vfs_zip/read/_read.rs.html#16) to make [vfs::filesystem::FileSystem](https://docs.rs/vfs/0.4.0/vfs/filesystem/trait.FileSystem.html) happy, since that requires my type to be Sync.

Switching to `IO: ReadAt` will be a breaking change for me, but it'll let me get rid of the Mutex.  Of course, the user can still provide a `Mutex<ReadAtMut>` - including `Mutex<File>` - but it'd be even nicer if I could have the user provide `SeeklessFile` and read/decompress from a zip in multiple threads simultaniously.

> Note that hard coded io::Result in trait methods is going to be refactored into an associated type for Error in version 0.2.
>
> Would it cause inconvenience for you?

That should be fine!  I'm already adapting several error types, one more shouldn't hurt 👍

**Comment by vi** [comment]
> 1. Simply impl ReadAt/WriteAt for File
> Could be hidden behind an opt-in feature?

How is the documentation supposed to look like in this case? Shall this impl be missing from docs.rs?

**Comment by MaulingMonkey** [comment]
tokio uses `#[doc(cfg(feature = "..."))]` to mark things as feature or OS specific.  doc(cfg(...)) is a nightly feature in an otherwise stable crate, so they hide it's usage behind a `docrs` config:

* Source example: https://docs.rs/tokio/0.2.22/src/tokio/macros/cfg.rs.html#115-116
* Rendered: https://docs.rs/tokio/0.2.22/tokio/fs/index.html

And then they enable that config for docs.rs specifically through their Config.toml:
```toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```

It's also possible to directly use the same CSS rules via inline HTML in your doc comments on stable, but I'm not sure how stable the CSS rule names are supposed to be.

**Comment by MaulingMonkey** [comment]
It turns out I need a mess of adapter types and traits anyways, so having one more for File isn't such a big deal.  Specifically, I need cheaply [Clone](https://doc.rust-lang.org/std/clone/trait.Clone.html)able [ReadAt](https://docs.rs/read_write_at/0.1.0/read_write_at/trait.ReadAt.html)s, and associated u64 lengths, so I ended up with [IntoCloneReadAtLen](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/into_clone_ral.rs#L15), which effectively transforms whatever I can get my hands on into "Seekless*" opaque wrappers around one of:

* [Arc\<File\>](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/seekless.rs#L11) (on windows/unix)
* [Arc<Mutex<Read + Seek>>](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/seekless.rs#L31) (also used for File when it doesn't implement read_at nor seek_read)
* [Arc<[u8]>](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/seekless.rs#L58) (or other cheaply cloneable AsRef<[u8]>s, including &[u8] without an Arc)

My wrappers for the first two types hide the internal file/io such that you can't observe seek state without, say, abusing [File::try_clone](https://doc.rust-lang.org/std/fs/struct.File.html#method.try_clone) first - which does seem a bit better than implementing ReadAt directly on File.  Similar could be implemented for WriteAt.  I've also got traits to go the other way:

* [struct ReadAtCursor](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/read_at_cursor.rs#L11) to adapt ReadAt back to Read+Seek
* [struct ReadRange](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/read_range.rs#L11) to create "slices" of another ReadAt/Read/Seek
* [struct ReadAtRef](https://github.com/MaulingMonkey/vfs-zip/blob/74da26a93c3eac22884a62bd8d70aab3434c9174/src/read/read_at_ref.rs#L7) to impl ReadAt for &ReadAt

Let me know if you'd like me to try and upstream any of this (and how\[1\]) - otherwise this issue can probably be closed.

\[1\]: my current handling of getting u64 lengths feels like quite the kludge - would be tempted to introduce a new:
```rust
trait IoLength    { fn len(&    self) -> Result<u64>; }
trait IoLengthMut { fn len(&mut self) -> Result<u64>; }
```

**Comment by MaulingMonkey** [comment]
I'm going to go ahead and close this, but let me know if you have specific PRs you'd like me to make in the future to upstream any of that.
